### PR TITLE
User Profile Dashboard Update: Contributions Lazy Loading on Demand.

### PR DESCRIPTION
**Pull request by creatrixity**
contributions lazy loading

### This pull updates the user profile dashboard.

On my previous pull, buttons for banning/unbanning users restricted by access levels and filtering articles according to their approval states were added..

Clicking the *Load More* button to load additional content has been added.

References [issue #35](https://github.com/knacksteem/knacksteem.org/issues/35)

### CODE REVIEW

**Comment by ogbiyoyosky** [comment]
Nice Work @creatrixity.  It seems there is a little bug on the filtering based on categories, please do check the filter mechanism other than everything looks good.
On the test, i can't seem to get the article with the category "art" which was posted.

**Comment by onozasi** [comment]
Well done @creatrixity. I noticed that when I logged in with "knowledges" account, it is not assigned the "sup" role by default.

**Comment by onozasi** [comment]
The following/follow tab should not redirect to steemit. Nothing should happen when these two tabs are clicked on, but they should perform the basic function of showing just the number of followed/followings.

**Comment by creatrixity** [comment]
Fixed the master supervisor access and also fixed the bug described by @ogbiyoyosky

**Comment by onozasi** [comment]
I am getting several errors each time I try going to kay's profile. I am not sure why this error pops up only on that user's profile. See gif below
http://localhost:3000/@kay


Also, the make sup, mod and ban function only appears on my profile. These functions should not appear on my profile page but on the profile page of others. See gif below.

The ban feature seems to work properly but its unclear to me why it's showing "ban kay" instead of the username of the user the "sup" wants to ban. E.g, I am currently on knowledges profile page, I expect to see "ban knowledges"

**Comment by creatrixity** [comment]
@onozasi I've just pushed a fix of all these issues. The reason why accessing @kay gives an error is because @kay does not exist on the STEEM blockchain at all.

**Comment by onozasi** [comment]
Alright. Another bug emerged. *[@kay](https://steemit.com/@kay)* is actually a valid Steem account. I am unable to describe the new bug but I've got a gif.

**Comment by creatrixity** [comment]
@onozasi Fixed the bug that pops up whenever accessing non-knacksteem users or undocumented users such as our queer and mysterious Mr. @kay who seems to have a reputation of 0 with no steem power or vests of any sort (after some investigation)

**Comment by creatrixity** [comment]
@onozasi Made a fix for that issue. Please check it out.

**Comment by onozasi** [comment]
Bravo! Everything seems to work correctly now.

**Pull request merged**
