### PR TITLE
Development of Voting slider 

### PR DESCRIPTION
**Pull request by snwolak**
voting_slider

add voting slider,
add redux reducer & action,
add getVoteWorth function,
add delay function

Voting slider is ready to be implemented whenever you want on the website,
it changes the value in the redux store (votingSlider.value) which you can use to cast the vote with a certain power.

To make it reusable you can use same function names which this component will get from higher order component for example handleConfirm on confirm button or something like that, so it would be reusable in settings and in casting a vote on a post.

### CODE REVIEW

**Comment by ogbiyoyosky** [comment]
@snwolak  I would like an explanation on how you hook up the users vote worth to this component.  From what i see, you are setting the state of the vote worth from the getVoteWorth function you created.

**Changes required.**

- There is already a function for getting Vote Worth Please check the services folder and uses to avoid duplication.

**Comment by ogbiyoyosky** [comment]
Other than the above, thumbs up everything look good.

**Comment by snwolak** [comment]
You answered your own question so nothing to add here. 
I have made changes accordingly to your request. 

Cheers.

**Comment by ogbiyoyosky** [comment]
I am getting this error please check
image
The ERROR is from the Function in the service which may not be your fault.

**Comment by snwolak** [comment]
Fixed and it was totally my fault, I forgot to change some property names

**Comment by ogbiyoyosky** [comment]
please fixed  the Little error on the console.
image

**Comment by ogbiyoyosky** [comment]
Nice work @snwolak, thanks for bearing with me. 
Good quality code from you. 
PR approved by @ogbiyoyosky.  @onozasi please proceed to merging.

**Pull request merged**
